
package nl.hu.generated_sources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FruitShopService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733/Design_Time_Addresses/FruitShopServiceLibrary/FruitShopService/?wsdl")
public class FruitShopService
    extends Service
{

    private final static URL FRUITSHOPSERVICE_WSDL_LOCATION;
    private final static WebServiceException FRUITSHOPSERVICE_EXCEPTION;
    private final static QName FRUITSHOPSERVICE_QNAME = new QName("http://tempuri.org/", "FruitShopService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8733/Design_Time_Addresses/FruitShopServiceLibrary/FruitShopService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRUITSHOPSERVICE_WSDL_LOCATION = url;
        FRUITSHOPSERVICE_EXCEPTION = e;
    }

    public FruitShopService() {
        super(__getWsdlLocation(), FRUITSHOPSERVICE_QNAME);
    }

    public FruitShopService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FRUITSHOPSERVICE_QNAME, features);
    }

    public FruitShopService(URL wsdlLocation) {
        super(wsdlLocation, FRUITSHOPSERVICE_QNAME);
    }

    public FruitShopService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FRUITSHOPSERVICE_QNAME, features);
    }

    public FruitShopService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FruitShopService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFruitShopService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFruitShopService")
    public IFruitShopService getBasicHttpBindingIFruitShopService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IFruitShopService"), IFruitShopService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFruitShopService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFruitShopService")
    public IFruitShopService getBasicHttpBindingIFruitShopService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IFruitShopService"), IFruitShopService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FRUITSHOPSERVICE_EXCEPTION!= null) {
            throw FRUITSHOPSERVICE_EXCEPTION;
        }
        return FRUITSHOPSERVICE_WSDL_LOCATION;
    }

}
